"""
pipeline/generate_lean.py

Emit NasaStd5001B/Generated/Bracket.lean from FEA results.

The generated file contains:
  · A concrete StructuralCheck definition with exact rational values.
  · Two margin-value theorems (for human readability and cross-checking).
  · Either bracket_compliant or bracket_noncompliant, proved by native_decide.

Ground truth: NASA-STD-5001B.md §3.2, §4.2d, §4.2.1 Table 1.
"""

from __future__ import annotations
from dataclasses import dataclass
from datetime import date
from fractions import Fraction
from pathlib import Path

from .cad_model import BracketGeometry, Material
from .fea import FEAResult


@dataclass(frozen=True)
class GenerateResult:
    """Margins and compliance verdict computed during Lean file generation."""
    ms_yield:  Fraction
    ms_ult:    Fraction
    compliant: bool


def _rat(f: Fraction) -> str:
    """Format a Fraction as a Lean rational literal."""
    if f.denominator == 1:
        return str(f.numerator)
    return f"{f.numerator} / {f.denominator}"


def _margin(allowable: Fraction, sigma: Fraction, df: Fraction) -> Fraction:
    """MS = allowable / (sigma × df) − 1."""
    return allowable / (sigma * df) - 1


def generate(
    geom: BracketGeometry,
    mat: Material,
    approach: str,           # "prototype" or "protoflight"
    limit_load_n: float,
    fea: FEAResult,
    out_path: Path,
) -> GenerateResult:
    """Write the generated Bracket.lean file and return the computed margins."""
    σ = fea.sigma_max_rational

    # Design factors from Table 1
    if approach == "prototype":
        df_yield   = Fraction(1)
        df_ultimate = Fraction(7, 5)
        approach_lean = ".prototype"
    else:
        df_yield    = Fraction(5, 4)
        df_ultimate = Fraction(7, 5)
        approach_lean = ".protoflight"

    ms_yield = _margin(mat.Fty, σ, df_yield)
    ms_ult   = _margin(mat.Ftu, σ, df_ultimate)

    compliant = ms_yield >= 0 and ms_ult >= 0

    if compliant:
        compliance_theorem = (
            "/-- The bracket complies with NASA-STD-5001B §4.2d: \n"
            "    both yield and ultimate margins are non-negative. -/\n"
            "theorem bracket_compliant : bracket.isCompliant := by native_decide"
        )
    else:
        # Report which conjuncts fail for clarity
        failures = []
        if ms_yield < 0:
            failures.append(f"yield MS = {float(ms_yield):.4f}")
        if ms_ult < 0:
            failures.append(f"ultimate MS = {float(ms_ult):.4f}")
        compliance_theorem = (
            f"/-- The bracket does NOT comply with NASA-STD-5001B §4.2d.\n"
            f"    Failing margin(s): {', '.join(failures)} -/\n"
            "theorem bracket_noncompliant : ¬ bracket.isCompliant := by native_decide"
        )

    lines = [
        "/-",
        "  NasaStd5001B.Generated.Bracket",
        f"  Auto-generated by pipeline/run.py on {date.today()}",
        "  DO NOT EDIT — re-run the pipeline to regenerate.",
        "",
        f"  Geometry : {float(geom.width):.0f} mm × {float(geom.height):.0f} mm "
        f"cross-section, {float(geom.length):.0f} mm cantilever",
        f"  Material : {mat.name}  (Fty = {mat.Fty} MPa, Ftu = {mat.Ftu} MPa)",
        f"  Approach : {approach}",
        f"  Limit load: {limit_load_n:.0f} N  (FEA applied at exactly this load, §3.2)",
        "",
        f"  FEA solver   : CalculiX 2.14",
        f"  Mesh         : {fea.n_nodes} nodes, {fea.n_elements} C3D4 elements",
        f"  Raw σ_max    : {fea.sigma_max_float:.4f} MPa  (max von Mises over all elements)",
        f"  Conservative : {fea.sigma_max_rational} MPa  (ceil to 0.001 MPa)",
        "",
        f"  Trust boundary: Lean verifies arithmetic given σ_max = {_rat(σ)}.",
        "  Correctness of the FEA model (mesh quality, BCs, solver convergence)",
        "  is established separately by comparison with beam theory σ = 6FL/bh².",
        "-/",
        "",
        "import NasaStd5001B.Defs",
        "",
        "namespace NasaStd5001B.Generated",
        "",
        "open NasaStd5001B",
        "",
        "-- ---------------------------------------------------------------------------",
        "-- Concrete bracket definition",
        "-- ---------------------------------------------------------------------------",
        "",
        "def bracket : StructuralCheck := {",
        f"  σ_max         := {_rat(σ)}",
        f"  σ_yield_allow := {_rat(mat.Fty)}",
        f"  σ_ult_allow   := {_rat(mat.Ftu)}",
        f"  approach      := {approach_lean} }}",
        "",
        "-- ---------------------------------------------------------------------------",
        "-- Margin values (for readability and cross-checking)",
        "-- ---------------------------------------------------------------------------",
        "",
        f"-- MS_yield = {mat.Fty} / ({_rat(σ)} * {_rat(df_yield)}) - 1 = {_rat(ms_yield)}",
        f"theorem bracket_yield_margin : bracket.yieldMargin = {_rat(ms_yield)} := by",
        "  native_decide",
        "",
        f"-- MS_ult = {mat.Ftu} / ({_rat(σ)} * {_rat(df_ultimate)}) - 1 = {_rat(ms_ult)}",
        f"theorem bracket_ultimate_margin : bracket.ultimateMargin = {_rat(ms_ult)} := by",
        "  native_decide",
        "",
        "-- ---------------------------------------------------------------------------",
        "-- Compliance certificate  (§4.2d)",
        "-- ---------------------------------------------------------------------------",
        "",
        compliance_theorem,
        "",
        "end NasaStd5001B.Generated",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    return GenerateResult(ms_yield=ms_yield, ms_ult=ms_ult, compliant=compliant)
